# Site
repository: Yoodahun/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Yoo Dahun
title: QA Engineer that advocates Quality.
email: dahun4032@gmail.com
website: https://velog.io/@dahunyoo

# Dark Mode (true/false/never)
darkmode: never

# Social links
#twitter_username: facespics
github_username:  Yoodahun
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: dahun-yoo
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Velog
  icon: fas fa-book-open
  url: https://velog.io/@dahunyoo
- title: Download PDF
  icon: fas fa-file-pdf
  url: https://yoodahun.github.io/resume_pdf/yoodahun_resume.pdf

# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
#about_title: About Me
about_profile_image: images/IMG_9608.jpg
about_content: | # this will include new lines to allow paragraphs
  안녕하세요! 3년차 QA Engineer로 활동하고 있는 **유다훈** 이라고 합니다.
  현재 일본 후쿠오카에서 암호자산 판매 서비스의 Back-office feature로 유동성 관리기능과 정산기능을 담당하고 있습니다.

  테스트 대상과 테스트 환경 등에 맞추어 적절한 테스트 플랜과 테스트케이스를 설계 / 수립할 수 있으며 테스트상황에 따라 관계자들과 조정 후 적절히 테스트 일정을 조율, 제안할 수 있습니다.

  컴퓨터공학 지식과 코딩경험도 가지고 있으며 테스트 자동화 프레임워크에 대한 지식과, 일부 프레임워크를 사용하여 현업에서의 테스트 자동화 경험을 가지고 있습니다. 이로 인하여 테스트 대상에 대한 효율적인 테스트 방법을 제안할 수 있으며 테스트 자동화를 구축할 수 있습니다.

  주식, 펀드 및 암호자산 서비스에서의 활동경험을 바탕으로한, 금융계열과 블록체인에 대한 도메인 지식을 가지고 있으며 Business Level의 일본어를 구사할 수 있습니다.

  기획, 개발, 그 외 이해관계자들과의 커뮤니케이션을 통해 효율적인 품질개선, 달성 활동을 진행합니다.

  _품질_ 이란, 비단 QA engineer만이 보증하는 것이 아닌, 프로젝트 구성원 전부가 품질에 대한 의식을 가지고 있을때야 말로 보증된다고 생각합니다. 구성원들이 품질에 대해 인식하고, 품질을 끌어올릴 수 있도록 조정하고 조율하는 역할을 하고 싶습니다.
  비효율적인 프로세스가 있다면, 구성원과 다 같이 협의하고, 개선하고 싶습니다. 프로덕트에 대한 끊임없는 호기심을 통해 우수한 완성도를 추구하고, 최고의 사용자 경험을 제공하고 싶습니다.


  - _velog_ : [www.velog.io/@dahunyoo](www.velog.io/@dahunyoo)
  - _Linkedin_ : [https://www.linkedin.com/in/dahun-yoo](https://www.linkedin.com/in/dahun-yoo)
  - _Gmail_ : dahun4032@gmail.com


  <div style="text-align: right;"> _last update: 2021. 07_ </div>

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: LINE Fukuoka Corp.
#        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: QA Engineer
        caption: 2019. 10 - Present, Fukuoka, Japan
        quote: >
          전세계 AU 1억 2천여명 이상의 일본의 인프라 레벨 수준의 국민적 메신저 서비스
        description: | # this will include new lines to allow paragraphs
          ## **CryptoCurrency brokerage service back-office feature**
          - Managing E2E Test Schedule
          - Design Test Policy and Test Plan
          - Writing some other Test documents using Confluence on Korean, Japanese Business level.
          - Design and Implement Manual TestCase and TestScenario using Testrail
          - Design and Implement Automating E2E Test using Cucumber, Selenium, TestNG

          QA Process 및 Testcase에 대한 Review Process 정립

          ---

          #### _2020. 11_, _2021. 03_, LINE 자체 Wallet Platform으로의 자산이관
          - 자산이관 계획 Review
          - 테스트환경에서 개발팀과의 리허설 진행 후 자산이관 계획 Feedback
          - Real환경에서 무사고 <mark>자산이관</mark> 실현

          #### _2020. 08 ~ Present_, [E2E Regression Test 자동화](https://velog.io/@dahunyoo/Manual-QA-Engineer가-UI기반-E2E-회귀-테스트를-자동화-한-후기)
          - Cucumber, Selenium을 이용한 회귀 테스트 자동화 구현
          - 기존 Regression test 공수 대비 <mark>4~50%</mark> 단축

          #### _2020. 07_, LINE 발행 암호자산 (LINK) 상장
          - 신규 암호자산 상장에 따른 Wallet Structure, 정산기능 Review 및 Feedback

          #### _2020. 05_, 법령개정 대응으로 인한 Wallet Structure 변경
          - 일본 가상화폐 법령 개정으로 인한 시스템 구성 변경
          - Wallet Structure 변경으로 인한 유동성 관리 계획 Review 및 Feedback 진행

      - layout: left
        title: Pioneer Soft
        sub_title: System Engineer
        caption: 2018. 04 - 2019. 09, Fukuoka, Japan
        quote: >
          China Offshore 와의 Communication을 통한 개발을 진행하는 증권회사 프로덕트 개발
        description: | # this will include new lines to allow paragraphs
          ## **Related to Stock, Fund and Customer management system**
          - Implement Unit Test using JUnit
          - Design and Implement Integration Test
          - Build Test env on Linux server

          ---

          #### _2019. 07 ~ 2019. 09_, A사 펀드 구매 시스템 프로젝트
          - 기존 엑셀과 SVN으로 관리되던 Bug Tracking Process를 RubyMine으로 <mark>이전 제안 및 실행</mark>

          #### _2019. 02 ~ 2019. 06_, O지방은행 주식, 펀드, 채권거래 프로젝트
          #### _2018. 07 ~ 2019. 01_, D사 적립식 주식 구매 시스템 프로젝트

  - title: Personal Project and Portfolio # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 개인 블로그 - Velog
        link: https://velog.io/@dahunyoo/
        quote: >
          QA / Test 관련 문서뿐만 아니라 실제 업무에서 적용해보았던 기술들을 정리
        description: | # this will include new lines to allow paragraphs
          QA / Test 관련 문서들 및 각종 Technical한 내용들에 대해 꾸준히 정리하고 있습니다.
          Udemy에서 수강한 내용들을 정리하여 올리기도 합니다.

      - layout: left
        title: 업무에서 E2E Manual Regression Test를 자동화한 후기
        link: https://velog.io/@dahunyoo/Manual-QA-Engineer가-UI기반-E2E-회귀-테스트를-자동화-한-후기
        quote: >
          실제 업무에서 Regression Test를 자동화하는 과정에서 고민했던 점들, 자동화를 한 후에 느낀 점들을 기록.
        description: | # this will include new lines to allow paragraphs
          업무에서 Regression Test를 자동화하는 과정들과 그 과정에서 고민했던 것들, 자동화 후에 느낀 점들, 개선해야할 점들 등을 기재해보았습니다.

          업무에서의 자동화는 아래의 기술들을 이용하여 자동화하였습니다.
          - Selenium
          - Cucumber-JVM
          - TestNG
          - Maven
          - Testrail

      - layout: left
        title: API Test using BDD Framework on JAVA / Python
        quote: >
          Udemy의 Flask framework강의를 보며 만든 간단한 API server를 기반으로 한 API Test 구현
        description: | # this will include new lines to allow paragraphs
          Udemy의 Flask framework 강의를 보며 만든 간단한 API Server를 기반으로, BDD framework( _Cucumber_, _behave_) 를 이용한 User Scenario 상정 및 테스트 케이스를 작성하여 구현한
          API test입니다.
          - API Server : [https://github.com/Yoodahun/Practice-Flask-RESTful](https://github.com/Yoodahun/Practice-Flask-RESTful)

          기본적으로는 모든 Status code를 발생시켜 확인하는 것을 중심으로 하였으며 CRUD의 흐름으로 작성되어있습니다.

          JAVA는 Cucumber와 Rest Assured, Python은 behave와 requests를 사용하였습니다.
          - JAVA : [https://github.com/Yoodahun/APITest-using-Java-RestAssured-for-FlaskRESTful](https://github.com/Yoodahun/APITest-using-Java-RestAssured-for-FlaskRESTful)
          - Python : [https://github.com/Yoodahun/APITest-using-Python-behave-for-FlaskRESTful](https://github.com/Yoodahun/APITest-using-Python-behave-for-FlaskRESTful)

      - layout: left
        title: Test Policy, Test Plan and Testcase
        quote: >
          현재 업무에서 사용하고 있는 포맷으로 작성된, 테스트 정책, 테스트 계획 및 테스트 케이스
        description: | # this will include new lines to allow paragraphs
          현업에서 사용하고 있는 포맷으로 작성된 테스트 정책, 테스트 계획 및 테스트 케이스입니다. 포맷을 가장 비슷하게 구성할 수 있는 Notion으로 작성하였습니다.

          내용은 전부 임의로 작성하였으며, 테스트케이스 역시 특정한 프로덕트나 서비스를 지칭하지 않는, 임의의 서비스를 대상으로 한 테스트 케이스이며 Excel로 작성되어 있습니다.
          - [Test Policy](https://www.notion.so/Test-Policy-1e28b43c91c74a699c3772209cae3d6c)
          - [TestPlan and Testcase](https://www.notion.so/TestPlan-Testcase-9193ca7f9cbd48a3a45e9052d774506a)
            - Testcase는 TestPlan 본문 중간에 임베드 하여 첨부하였습니다.


          ----


#      - layout: left
#        title: Rails Tutorial Translation
#        link: github.com/Yoodahun/Rails_Tutorials_Translation
##        additional_links:
##          - title:  sproogen/modern-resume-theme
##            icon: fab fa-github
##            url: github.com/sproogen/modern-resume-theme
#          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
#          #   icon: fab fa-github
#          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#        quote: >
#          Michael Hartl 의 Ruby on Rails Tutorial 의 일어판을 한국어로 번역.
#        description: | # this will include new lines to allow paragraphs
#          단종된 _Ruby on Rails Tutorial_ 의 v4 일어판을 원작자의 허가를 얻어 번역해보았습니다. 현재는 Rails5의 release에 따라 개정된 상황입니다.
#
#          서점에서 일어판을 보게 되었는데 레일즈를 비롯한 Web의 기본구조에 대해서도 차근차근 설명해주고 있어서 번역에 도전해보게 되었습니다.
#
#          본 프로젝트는 Ruby on Rails Facebook group에도 공유되었습니다.
#          [원본의 링크입니다.](https://www.railstutorial.org/)
#

  - title: Skill # Title for the section
    layout: list # Type of content section (list/text)
    content:

        - layout: left
          title: Testing
          caption: Java, Python
          description: | # this will include new lines to allow paragraphs
            - Selenium, Appium
            - Cucumber, behave (BDD Framework)
            - REST Assured, requests, POSTMAN
            - Maven, TestNG, JUnit, Pytest
            - Jmeter
            - Testrail

        - layout: left
          title: Communication
          description: |
           - JIRA, Confluence, Zeplin, Slack, Notion

        - layout: left
          title: Others
          description: |
            - SQL
            - Git, SVN, Bash(Linux command)
            - Ruby on rails, Flask

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Udemy Online course
        caption: 2018 - Present
        link: udemy.com
        quote: >
          온라인 교육/강의 플랫폼 Udemy를 통하여 업무역량 강화를 위한 계속적인 자기계발
        description: |
          - REST APIs with Flask and Python
          - Python SDET - Backend RestAPITesting with BDD Framework
          - Elegant Automation Frameworks with Python and Pytest
          - Devops Fundamentals - CI/CD with AWS+Docker+Ansible+Jenkins
          - Learn JMETER from Scratch on Live Apps - Performance Testing
          - Rest APITesting from Scratch - ResetAssured Java
          - Postman - The Complete guide - REST API Testing
          - Cucumber with Java-Build Automation Framework in lesser code
          - Appium Frameworks -Mobile Automation Testing from Scracth
          - Selenium Webdriver with Java -Basics to Advanced Frameworks
          - Bash Shell Scripting: Crash Course for Beginners

      - layout: left
        title: SCSC
        caption: 2015 - 2019
        sub_title: Samsung Convergence Software Course.
        quote: >
          삼성에서 후원하는 비전공자전용 부전공 코스
        description: | # this will include new lines to allow paragraphs
          삼성에서 선정한 총 30학점의 부전공 코스를 수료하였습니다.
          주요 커리큘럼은 아래와 같습니다.
          - Computer Programming
          - Object-Oriented Design
          - Data Structure
          - Operating System
          - Database
          - Algorithms

      - layout: left
        title: Chungnam National Univ.
        sub_title: 충남대학교.
        caption: 2010 - 2018
        description: | # this will include new lines to allow paragraphs
          - Major : Japanese Language and Literature
          - Minor : Computer Science and Engineering



# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
