name: Generate_resume_to_pdf
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Webpage to PDF
        uses: markwilson/html2pdf@v1.0
        with:
          htmlPath: '_site/index.html'
          pdfName: 'test'
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Generate PDF