name: Generate_resume_to_pdf
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Webpage to PDF
        uses: misaelnieto/web_to_pdf_action@master
        with:
          webPageURL: https://yoodahun.github.io
          outputFile: resume/yoodahun_resume.pdf
          usePuppeteer: true
          pdfOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Generate PDF