name: resume to pdf

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on : ubuntu-latest
    steps:
    - name: html to pdf
      uses: fifsky/html-to-pdf-action@master
      with:
        htmlFile: ./_site/index.html
        outputFile: ./resume_pdf/yoodahun_resume.pdf
        pdfOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'
    - name : Generate and commit pdf
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: commit PDF
        branch: master
        file_pattern: resume_pdf/yoodahun_resume.pdf





