name: resume to pdf

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on : ubuntu-latest
    steps:
    - name: html to pdf
      uses: misaelnieto/web_to_pdf_action@v0.3.1
      with:
        webPageURL: https://yoodahun.github.io
        outputFile: ./yoodahun_resume.pdf
        usePuppeteer: true
        pdfOptions: '{"format": "Letter", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'
    - name : Generate and commit pdf
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: commit PDF
        branch: master
        file_pattern: ./yoodahun_resume.pdf
      - name: "Run if changes have been detected"
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        run: echo "Changes!"
      - name: "Run if no changes have been detected"
        if: steps.auto-commit-action.outputs.changes_detected == 'false'
        run: echo "No Changes!"






